### ISSUE TITLE
latest version crashing on second start up

### ISSUE THREAD

**Issue by starstriker0** [gavinsmod/gavinsextensiblemod#81]
**Describe the bug**
im using the mod in a modpack for the item esp functions, but I'm noticing that it boots up fine the first time, but the second time, it consistently crashes every time, I have to go in and delete the config files it generates to get it to start up properly again, I tried downgrading, and it starts, but the functions say their activated, except they arent, the latest one is the only one where the features work for me.

**To Reproduce**

1. Install the mod
3. run the game
4. exit
6. try to start the game a second time

**Expected behavior**
start properly each time the game is started

**Version Info (please complete the following information):**

- OS: Windows
- Mod Version: v1.4.8rc2

**Additional context**
the crash logs if you need them: https://pastebin.com/p5zsRxhb

**Comment by GT3CH1** [comment]
Thanks for the heads up! I'll investigate this as soon as I am able to.

**Comment by starstriker0** [comment]
👍

**Comment by GT3CH1** [comment]
Hey,

I am unfortunately unable to reproduce the issue using v1.4.8-rc2. v1.4.7 and below had a bug where the ESP engine wouldn't render in some cases. 

Would you be able to do the following?

1. Please attach a list of the mods loaded in your client. Sometimes some mods play well with gavinsmod, other's don't.
2. Delete any other versions of gavinsmod you may have in your mods folder.
3. Download a fresh copy of v1.4.8rc2 here: [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc2](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc2)

Please not that v1.4.8-rc2 is currently built for Minecraft 1.21.1 - I am working on updating it to 1.21.3 here shortly.

**Comment by starstriker0** [comment]
oh, sure, heres the list of mods and versions
[Southgate SMP Modpack 1.21.csv](https://github.com/user-attachments/files/17688584/Southgate.SMP.Modpack.1.21.csv)
and, the exact mod files folder if you want it

there arent any other versions of gavinsmod installed

and, I'm using mc version 1.21 not 1.21.1 or above, so I thought that might be the reason, but it doesn't explain why the mod works when there's no config files

**Comment by starstriker0** [comment]
just downloaded a fresh copy, same problem, works fine on the first run(the one without config files) but then on the second run(with config files) it crashes

**Comment by GT3CH1** [comment]
Just to clarify - are you running Minecraft 1.21 or 1.21**.1** where this issue is occurring?

**Comment by starstriker0** [comment]
i am running minecraft 1.21, but like i said, the mod runs fine the first time with no problems, without its config files, so its not a Minecraft version compatibility issue

**Comment by GT3CH1** [comment]
I am unable to reproduce this issue using 1.4.8-rc2 _with_ Minecraft 1.21.

Would you be able to attach the settings.json generated after the first launch and when the crash occurs (eg, the settings file before and after)? It's under `%APPDATA%/.minecraft/mods/gavinsmod`. I am suspecting that one of those mods that you sent me earlier are doing something funny with the X-Ray feature which is causing the crash.

**Comment by starstriker0** [comment]
im so sorry i didn't notice you replied until now
here's the file after the first run
[settings.json](https://github.com/user-attachments/files/17690008/settings.json)
and here it is after the crash
[settings.json](https://github.com/user-attachments/files/17690011/settings.json)
crash logs again just incase
[crash-2024-11-09_22.07.47-client.txt](https://github.com/user-attachments/files/17690014/crash-2024-11-09_22.07.47-client.txt)

**Comment by GT3CH1** [comment]
Thanks for those files. I'll be trying to sort out this out, it seems like its going to be a bit of a rabbit hole of a bug to sort out, since I am unable to reproduce this issue locally. Thanks for those files. I'll keep you updated as I find more out.

**Comment by starstriker0** [comment]
👍

**Comment by GT3CH1** [comment]
I actually think I figured out what was going on - I've made a new release under the releases page. Please grab a new copy of the mod here: [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc3](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc3) - Make sure to NOT use the file ending in `-sources.jar`

**Comment by starstriker0** [comment]
ok, ill try it

**Comment by starstriker0** [comment]
nope, didnt fix it, ive replaced the mod but its having the same problem, I still have to delete the config files for it boot up a second time, I tried everything short of reinstalling the Minecraft instance even deleting everything in the configs folder that should have no relation
[crash-2024-11-10_18.42.08-client.txt](https://github.com/user-attachments/files/17693642/crash-2024-11-10_18.42.08-client.txt)
full logs if you want
https://mclo.gs/OoYAbHC

**Comment by GT3CH1** [comment]
Thanks for the crash report - this looks like it's an issue with prism
launcher compatibility. I'll try and take a look into it.

**Comment by starstriker0** [comment]
which launcher do you use? because i just copied the mods folder over to ATlauncher and had the same issue

**Comment by GT3CH1** [comment]
I usually just use the default Minecraft launcher. I installed ATlauncher today, and I created an instance with the following jar files installed in the mods folder for the instance:

* fabric-api-0.102.0+1.21.jar
* fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
* gavinsmod-1.4.8-rc3+1.21.1-dev.jar

Here's what I did:
1. Loaded into the game
2. Made changes to the config file
3. Stopped the game
4. Started the game
5. Loaded back into the game

And the client did not crash. I also copy+pasted the configs you gave me, and tried the downgrading to v1.4.8-rc2, and the client still did not crash.

 I then googled the error message provided (`Caused by: com.google.gson.JsonIOException: Failed making field 'java.util.Optional#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.`) and this actually might be caused by a dependency of my mod needing to be updated - I've since made the change (as seen in commit 1bd0d93e) and have built this on my CI server. I have attached the new build titled `gavinsmod-1.4.8-rc4+1.21.1-dev.jar` on the releases page here: [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc4](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc4)

Would you be able to try that version and let me know if it crashes again? If it does, I may have to _downgrade_ the dependency rather than update it. We shall see.

Thanks for helping out on this, I do appreciate it!

**Comment by starstriker0** [comment]
nope, still having the same issue, honestly, im at a loss for whats wrong, but I did decide to record it this time
https://github.com/user-attachments/assets/0dcd5e19-b384-48be-9a9f-aa8242f12035

and here are the crash logs for this attempt, ill try with prism launcher again but I don't think it'll work
[crash-2024-11-11_21.29.42-client.txt](https://github.com/user-attachments/files/17710978/crash-2024-11-11_21.29.42-client.txt)

**Comment by GT3CH1** [comment]
I'm at a loss too - I'll have to dig into it a bit more. I'm suspecting
that one of the mods in the list you gave me is causing some sort of weird
compatibility problem. I'll update you as I find out more.

**Comment by GT3CH1** [comment]
I have been able to reproduce the issue by downloading and activating one of the following mods:

* Gamma Utils 
* worldweaver 
* YungsApi
* YetAnotherConfigLib
* YouDied
* Zoomify
* libIPN
* owo

**Comment by GT3CH1** [comment]
Update: This appears to be a compatibility issue with owo-lib.

**Comment by GT3CH1** [comment]
I believe I have fixed this issue, since I am no longer crashing with owo-lib installed running along side my client.

Please check here for the rc5 release (again - make sure to not download the -sources file!) [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc5](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc5)

**Comment by GT3CH1** [comment]
Hey I just wanted to make sure that you saw my previous message. 

> I believe I have fixed this issue, since I am no longer crashing with owo-lib installed running along side my client.
> Please check here for the rc5 release (again - make sure to not download the -sources file!) https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc5

**Comment by starstriker0** [comment]
Oh, shoot, sorry, had exams going on so I wasn't paying attention, I'll check it out later today

**Comment by GT3CH1** [comment]
No worries. I hope they went well.

**Comment by starstriker0** [comment]
it works!! thank you!

**Comment by GT3CH1** [comment]
Awesome, thanks! Please feel free to open another issue if you find a bug/have a cool idea for the mod.
